### ISSUE TITLE
Password leak

### ISSUE THREAD

**Issue by maciok** [mannyhenri/react-example#1]
I found this repository through your `linkedin` course. 
You should not advice your viewers to publish their passwords in github ( I'm pointing at your travis config and docker password ). It'd be beneficial to present correct way of doing such configuration e.g.  [Travis documentation](https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry)

**Comment by mannyhenri** [comment]
I typically don't or mention that the password won't be good afterwards (in this case it isn't) but thanks good catch
